# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import screening_pb2 as screening__pb2

GRPC_GENERATED_VERSION = '1.75.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in screening_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ScreeningServiceStub(object):
    """ScreeningService provides the main interface for candidate screening
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartScreening = channel.unary_unary(
                '/talentpilot.screening.ScreeningService/StartScreening',
                request_serializer=screening__pb2.StartScreeningRequest.SerializeToString,
                response_deserializer=screening__pb2.StartScreeningResponse.FromString,
                _registered_method=True)
        self.GetNextQuestion = channel.unary_unary(
                '/talentpilot.screening.ScreeningService/GetNextQuestion',
                request_serializer=screening__pb2.GetNextQuestionRequest.SerializeToString,
                response_deserializer=screening__pb2.GetNextQuestionResponse.FromString,
                _registered_method=True)
        self.SubmitAnswer = channel.unary_unary(
                '/talentpilot.screening.ScreeningService/SubmitAnswer',
                request_serializer=screening__pb2.SubmitAnswerRequest.SerializeToString,
                response_deserializer=screening__pb2.SubmitAnswerResponse.FromString,
                _registered_method=True)
        self.GetScreeningResult = channel.unary_unary(
                '/talentpilot.screening.ScreeningService/GetScreeningResult',
                request_serializer=screening__pb2.GetScreeningResultRequest.SerializeToString,
                response_deserializer=screening__pb2.GetScreeningResultResponse.FromString,
                _registered_method=True)
        self.StreamScreeningProgress = channel.unary_stream(
                '/talentpilot.screening.ScreeningService/StreamScreeningProgress',
                request_serializer=screening__pb2.StreamScreeningProgressRequest.SerializeToString,
                response_deserializer=screening__pb2.ScreeningProgressUpdate.FromString,
                _registered_method=True)


class ScreeningServiceServicer(object):
    """ScreeningService provides the main interface for candidate screening
    """

    def StartScreening(self, request, context):
        """Start a new screening session for a candidate
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNextQuestion(self, request, context):
        """Get the next question for the current screening session
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitAnswer(self, request, context):
        """Submit an answer and get the next question or assessment
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetScreeningResult(self, request, context):
        """Get the final screening assessment and email draft
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamScreeningProgress(self, request, context):
        """Stream real-time screening progress updates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScreeningServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartScreening': grpc.unary_unary_rpc_method_handler(
                    servicer.StartScreening,
                    request_deserializer=screening__pb2.StartScreeningRequest.FromString,
                    response_serializer=screening__pb2.StartScreeningResponse.SerializeToString,
            ),
            'GetNextQuestion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNextQuestion,
                    request_deserializer=screening__pb2.GetNextQuestionRequest.FromString,
                    response_serializer=screening__pb2.GetNextQuestionResponse.SerializeToString,
            ),
            'SubmitAnswer': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitAnswer,
                    request_deserializer=screening__pb2.SubmitAnswerRequest.FromString,
                    response_serializer=screening__pb2.SubmitAnswerResponse.SerializeToString,
            ),
            'GetScreeningResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScreeningResult,
                    request_deserializer=screening__pb2.GetScreeningResultRequest.FromString,
                    response_serializer=screening__pb2.GetScreeningResultResponse.SerializeToString,
            ),
            'StreamScreeningProgress': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamScreeningProgress,
                    request_deserializer=screening__pb2.StreamScreeningProgressRequest.FromString,
                    response_serializer=screening__pb2.ScreeningProgressUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'talentpilot.screening.ScreeningService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('talentpilot.screening.ScreeningService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ScreeningService(object):
    """ScreeningService provides the main interface for candidate screening
    """

    @staticmethod
    def StartScreening(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/talentpilot.screening.ScreeningService/StartScreening',
            screening__pb2.StartScreeningRequest.SerializeToString,
            screening__pb2.StartScreeningResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNextQuestion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/talentpilot.screening.ScreeningService/GetNextQuestion',
            screening__pb2.GetNextQuestionRequest.SerializeToString,
            screening__pb2.GetNextQuestionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitAnswer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/talentpilot.screening.ScreeningService/SubmitAnswer',
            screening__pb2.SubmitAnswerRequest.SerializeToString,
            screening__pb2.SubmitAnswerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetScreeningResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/talentpilot.screening.ScreeningService/GetScreeningResult',
            screening__pb2.GetScreeningResultRequest.SerializeToString,
            screening__pb2.GetScreeningResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamScreeningProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/talentpilot.screening.ScreeningService/StreamScreeningProgress',
            screening__pb2.StreamScreeningProgressRequest.SerializeToString,
            screening__pb2.ScreeningProgressUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
