"""Skill aliases and adjacent-skill mappings for matching."""

# Canonical aliases: map common variations to a canonical form.
# All keys and values are lowercase.
SKILL_ALIASES: dict[str, str] = {
    "react.js": "react",
    "reactjs": "react",
    "react js": "react",
    "vue.js": "vue",
    "vuejs": "vue",
    "vue js": "vue",
    "angular.js": "angular",
    "angularjs": "angular",
    "node.js": "node",
    "nodejs": "node",
    "node js": "node",
    "next.js": "nextjs",
    "nextjs": "nextjs",
    "express.js": "express",
    "expressjs": "express",
    "jquery": "jquery",
    "k8s": "kubernetes",
    "k8": "kubernetes",
    "postgres": "postgresql",
    "psql": "postgresql",
    "pg": "postgresql",
    "mongo": "mongodb",
    "mssql": "sql server",
    "ms sql": "sql server",
    "golang": "go",
    "js": "javascript",
    "ts": "typescript",
    "py": "python",
    "rb": "ruby",
    "tf": "terraform",
    "aws lambda": "aws",
    "amazon web services": "aws",
    "gcp": "google cloud",
    "google cloud platform": "google cloud",
    "azure devops": "azure",
    "ms azure": "azure",
    "tailwind": "tailwind css",
    "tailwindcss": "tailwind css",
    "scss": "sass",
    "jest": "jest",
    "cypress.io": "cypress",
    "playwright": "playwright",
    "gh actions": "github actions",
    "github ci": "github actions",
    "gitlab ci": "gitlab",
    "docker compose": "docker",
    "compose": "docker",
    "helm charts": "helm",
    "kafka streams": "kafka",
    "spark streaming": "spark",
    "pyspark": "spark",
    "torch": "pytorch",
    "py torch": "pytorch",
    "sklearn": "scikit-learn",
    "sk learn": "scikit-learn",
    "nlp": "natural language processing",
    "cv": "computer vision",
    "figma": "figma",
    "sketch": "sketch",
    "xd": "adobe xd",
    "adobe creative suite": "adobe creative suite",
    "photoshop": "adobe creative suite",
    "illustrator": "adobe creative suite",
    "jira": "jira",
    "confluence": "confluence",
    "notion": "notion",
    "graphql": "graphql",
    "grpc": "grpc",
    "rest": "rest api",
    "restful": "rest api",
    "rest api": "rest api",
    "api design": "rest api",
    "microservices": "microservices",
    "micro services": "microservices",
    "ci/cd": "ci/cd",
    "cicd": "ci/cd",
    "continuous integration": "ci/cd",
    "continuous deployment": "ci/cd",
    "a/b testing": "a/b testing",
    "ab testing": "a/b testing",
    "machine learning": "machine learning",
    "ml": "machine learning",
    "deep learning": "deep learning",
    "dl": "deep learning",
    "computer vision": "computer vision",
    "natural language processing": "natural language processing",
    "data engineering": "data engineering",
    "data science": "data science",
    "devops": "devops",
    "sre": "site reliability engineering",
    "site reliability": "site reliability engineering",
    "technical writing": "technical writing",
    "product management": "product management",
    "ui/ux design": "ui/ux design",
    "ux design": "ui/ux design",
    "ui design": "ui/ux design",
    "design systems": "design systems",
    "test automation": "test automation",
    "qa automation": "test automation",
    "selenium webdriver": "selenium",
    "ios development": "ios",
    "android development": "android",
    "react native": "react native",
    "react-native": "react native",
    "embedded systems": "embedded systems",
    "rtos": "rtos",
    "real-time operating system": "rtos",
    "distributed systems": "distributed systems",
    "distributed computing": "distributed systems",
    "blockchain": "blockchain",
    "web3": "blockchain",
    "smart contracts": "smart contracts",
    "solidity": "solidity",
    "ethereum": "ethereum",
    "security": "security",
    "cybersecurity": "security",
    "infosec": "security",
    "observability": "observability",
    "monitoring": "observability",
    "public speaking": "public speaking",
    "presentation skills": "public speaking",
    "community building": "community building",
    "program management": "program management",
    "cross-functional leadership": "cross-functional leadership",
    "cross functional leadership": "cross-functional leadership",
    "customer facing": "customer facing",
    "customer-facing": "customer facing",
    "architecture": "architecture",
    "system design": "architecture",
    "software development": "software development",
    "software engineering": "software development",
    "user research": "user research",
    "ux research": "user research",
    "prototyping": "prototyping",
    "wireframing": "prototyping",
    "a/b testing": "a/b testing",
    "roadmapping": "roadmapping",
    "roadmap": "roadmapping",
    "3d graphics": "3d graphics",
    "3d rendering": "3d graphics",
    "shaders": "shaders",
    "shader programming": "shaders",
    "video production": "video production",
    "video editing": "video production",
}


def normalize_skill(name: str) -> str:
    """Normalize a skill name to its canonical form."""
    lower = name.strip().lower()
    return SKILL_ALIASES.get(lower, lower)


# Adjacent skills: skills that are similar/transferable.
# Each entry maps a canonical skill to a set of canonical adjacent skills.
# Used for partial-match bonus scoring.
ADJACENT_SKILLS: dict[str, set[str]] = {
    # Languages
    "python": {"ruby", "go", "typescript", "javascript"},
    "javascript": {"typescript", "python"},
    "typescript": {"javascript"},
    "java": {"kotlin", "scala", "c#"},
    "kotlin": {"java", "swift"},
    "swift": {"kotlin", "dart"},
    "go": {"rust", "python", "c"},
    "rust": {"go", "c++", "c"},
    "c": {"c++", "rust"},
    "c++": {"c", "rust", "java"},
    "ruby": {"python", "javascript"},
    "php": {"javascript", "python"},
    "dart": {"javascript", "swift", "kotlin"},
    "sql": {"postgresql", "mysql", "sql server"},
    # Frameworks
    "react": {"vue", "angular", "svelte", "nextjs"},
    "vue": {"react", "angular", "svelte", "nuxt"},
    "angular": {"react", "vue"},
    "svelte": {"react", "vue"},
    "nextjs": {"react", "nuxt"},
    "nuxt": {"vue", "nextjs"},
    "express": {"fastify", "koa", "nestjs"},
    "fastapi": {"flask", "django", "express"},
    "flask": {"fastapi", "django"},
    "django": {"flask", "fastapi"},
    "spring boot": {"quarkus", "micronaut"},
    "rails": {"django", "express"},
    "react native": {"flutter", "swift", "kotlin"},
    "flutter": {"react native", "dart"},
    "pytorch": {"tensorflow"},
    "tensorflow": {"pytorch"},
    "scikit-learn": {"pytorch", "tensorflow"},
    # Databases
    "postgresql": {"mysql", "sql server", "sqlite"},
    "mysql": {"postgresql", "sql server", "mariadb"},
    "mongodb": {"couchdb", "dynamodb"},
    "redis": {"memcached"},
    "sqlite": {"postgresql", "mysql"},
    "cassandra": {"scylladb"},
    "dynamodb": {"mongodb", "firebase"},
    "snowflake": {"bigquery", "redshift"},
    "bigquery": {"snowflake", "redshift"},
    "redshift": {"snowflake", "bigquery"},
    # Cloud & Infra
    "aws": {"azure", "google cloud"},
    "azure": {"aws", "google cloud"},
    "google cloud": {"aws", "azure"},
    "kubernetes": {"docker", "nomad"},
    "docker": {"kubernetes", "podman"},
    "terraform": {"pulumi", "cloudformation"},
    "ansible": {"terraform", "puppet", "chef"},
    "ci/cd": {"github actions", "gitlab", "jenkins"},
    "github actions": {"ci/cd", "gitlab", "jenkins"},
    "gitlab": {"github actions", "jenkins", "ci/cd"},
    "jenkins": {"github actions", "gitlab", "ci/cd"},
    "prometheus": {"grafana", "datadog"},
    "grafana": {"prometheus", "datadog"},
    "datadog": {"prometheus", "grafana"},
    "airflow": {"prefect", "dagster"},
    "kafka": {"rabbitmq", "pulsar"},
    "spark": {"flink", "hadoop"},
    # Skills
    "rest api": {"graphql", "grpc"},
    "graphql": {"rest api", "grpc"},
    "grpc": {"graphql", "rest api"},
    "microservices": {"monolith", "serverless"},
    "serverless": {"microservices", "aws lambda"},
    "machine learning": {"deep learning", "data science"},
    "deep learning": {"machine learning", "computer vision", "natural language processing"},
    "computer vision": {"deep learning", "image processing"},
    "natural language processing": {"deep learning", "machine learning"},
    "data engineering": {"data science", "machine learning"},
    "data science": {"machine learning", "data engineering"},
    "devops": {"site reliability engineering", "platform engineering"},
    "site reliability engineering": {"devops", "platform engineering"},
    "security": {"devops", "site reliability engineering"},
    "observability": {"devops", "site reliability engineering"},
    "test automation": {"qa automation", "selenium", "playwright", "cypress"},
    "selenium": {"playwright", "cypress", "test automation"},
    "playwright": {"selenium", "cypress", "test automation"},
    "cypress": {"selenium", "playwright", "test automation"},
    "ui/ux design": {"product design", "interaction design", "figma"},
    "figma": {"sketch", "adobe xd", "ui/ux design"},
    "design systems": {"ui/ux design", "figma"},
    "user research": {"ui/ux design", "product management"},
    "product management": {"program management", "user research"},
    "technical writing": {"documentation", "api documentation"},
    "public speaking": {"presentation skills", "community building"},
    "ios": {"swift", "react native", "flutter"},
    "android": {"kotlin", "react native", "flutter"},
    "embedded systems": {"rtos", "c", "c++"},
    "distributed systems": {"microservices", "architecture"},
    "architecture": {"distributed systems", "system design"},
}
